/*  =========================================================================
    issue-rcv - generated layer of public API

    Copyright (C) 2014 - 2018 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ISSUE_RCV_LIBRARY_H_INCLUDED
#define ISSUE_RCV_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <fty_log.h>
#include <ftyproto.h>

//  ISSUE_RCV version macros for compile-time API detection
#define ISSUE_RCV_VERSION_MAJOR 1
#define ISSUE_RCV_VERSION_MINOR 0
#define ISSUE_RCV_VERSION_PATCH 0

#define ISSUE_RCV_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ISSUE_RCV_VERSION \
    ISSUE_RCV_MAKE_VERSION(ISSUE_RCV_VERSION_MAJOR, ISSUE_RCV_VERSION_MINOR, ISSUE_RCV_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ISSUE_RCV_STATIC
#       define ISSUE_RCV_EXPORT
#   elif defined ISSUE_RCV_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ISSUE_RCV_EXPORT __declspec(dllexport)
#       else
#           define ISSUE_RCV_EXPORT
#       endif
#   elif defined ISSUE_RCV_EXPORTS
#       define ISSUE_RCV_EXPORT __declspec(dllexport)
#   else
#       define ISSUE_RCV_EXPORT __declspec(dllimport)
#   endif
#   define ISSUE_RCV_PRIVATE
#elif defined (__CYGWIN__)
#   define ISSUE_RCV_EXPORT
#   define ISSUE_RCV_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ISSUE_RCV_PRIVATE __attribute__ ((visibility ("hidden")))
#       define ISSUE_RCV_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define ISSUE_RCV_PRIVATE
#       define ISSUE_RCV_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ISSUE_RCV_BUILD_DRAFT_API
#define ISSUE_RCV_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ISSUE_RCV_BUILD_DRAFT_API
typedef struct _issue_rcv_server_t issue_rcv_server_t;
#define ISSUE_RCV_SERVER_T_DEFINED
#endif // ISSUE_RCV_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ISSUE_RCV_BUILD_DRAFT_API
#include "issue_rcv_server.h"
#endif // ISSUE_RCV_BUILD_DRAFT_API

#ifdef ISSUE_RCV_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
ISSUE_RCV_EXPORT void
    issue_rcv_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // ISSUE_RCV_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
